name: Build & Deploy SWI Map

on:
  push:
    branches:
      - main
    paths:
      - 'make_swi.py'
      - 'requirements.txt'
      - 'index.html'
      - 'swi_overlay.png'
      - 'swi_meta.json'
      - '.github/workflows/deploy.yml'
      - 'data/**'        # any files in your data folder
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build SWI overlay
        run: python make_swi.py

      - name: Prepare publish folder
        run: |
          mkdir -p public
          cp index.html public/
          cp swi_overlay.png swi_meta.json public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
